[project]
name = 'Simulation-Hypothesis-Validation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.reality-consistency-check]
path = 'contracts/reality-consistency-check.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulation-boundary-testing]
path = 'contracts/simulation-boundary-testing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
